version: '3.5'

networks:
  bot:
    name: bot
    driver: bridge  

services:
  db:
    container_name: db
    image: postgres:14.2-alpine
    restart: always
    command: ["postgres", "-p", "${DB_PORT}"]
    networks:
        - bot
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        - ~/db-data:/var/lib/postgresql/data

  pgbouncer:
    container_name: pgbouncer
    image: docker.io/bitnami/pgbouncer
    environment:
      POSTGRESQL_USERNAME: ${DB_USERNAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      PGBOUNCER_DATABASE: ${DB_DATABASE}
      POSTGRESQL_HOST: db
    networks:
      - bot