version: '3.5'

networks:
  bot:
    name: bot
    driver: bridge
    external: true

services:
  api:
    build:
      context: .
      dockerfile: build/golang/Dockerfile
    environment:
      - PGBOUNCER_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@pgbouncer:${PGBOUNCER_PORT}/${DB_DATABASE}?sslmode=disable
      - POSTGRESQL_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}?sslmode=disable
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - bot