version: '3.5'

networks:
  bot:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: build/golang/Dockerfile
    environment:
      - PGBOUNCER_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@pgbouncer:${PGBOUNCER_PORT}/${DB_DATABASE}?sslmode=disable
      - POSTGRESQL_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}?sslmode=disable
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    networks:
      - bot