version: '3.5'

networks:
  bot:
    name: bot
    driver: bridge
    external: true

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: build/golang/Dockerfile_prod
    environment:
      - PGBOUNCER_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@pgbouncer:${PGBOUNCER_PORT}/${DB_DATABASE}?sslmode=disable
      - POSTGRESQL_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}?sslmode=disable
    restart: unless-stopped
    image: registry.gitlab.com/back1ng1/question-bot-api:main
    ports:
      - "3000:3000"
    networks:
      - bot
    volumes:
      - ./.env:/usr/src/app/.env