version: '3.5'

networks:
  bot:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: build/golang/Dockerfile_prod
    environment:
      - POSTGRESQL_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@pgbouncer:${PGBOUNCER_PORT}/${DB_DATABASE}
    restart: unless-stopped
    image: registry.gitlab.com/back1ng1/question-bot-api:main
    ports:
      - "3000:3000"
    networks:
      - bot
    volumes:
      - ./.env:/usr/src/app/.env

  db:
    container_name: db
    image: postgres:14.2-alpine
    restart: always
    command: ["postgres", "-p", "${DB_PORT}"]
    networks:
        - bot
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        - ~/db-data:/var/lib/postgresql/data

  pgbouncer:
    container_name: pgbouncer
    image: docker.io/bitnami/pgbouncer
    environment:
      POSTGRESQL_USERNAME: ${DB_USERNAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      PGBOUNCER_DATABASE: ${DB_DATABASE}
      POSTGRESQL_HOST: db
    networks:
      - bot